apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: serverless-stack
  title: Serverless Stack (SQS → Lambda → S3)
spec:
  owner: platform-team
  type: infrastructure

  parameters:
    - title: Informações
      required:
        - projectName
      properties:
        projectName:
          type: string
          title: Nome do Projeto

  steps:
    - id: fetchBase
      name: Clonando base
      action: fetch:template
      input:
        url: ./skeleton
        values:
          projectName: ${{ parameters.projectName }}

    - id: publish
      name: Publicando no Git
      action: publish:github
      input:
        repoUrl: d2odpiejt3zpvd.cloudfront.net:443/gitea?repo=${{parameters.projectName}}
        defaultBranch: main
        description: Stack serverless com SQS, Lambda e S3
    - id: create-argocd-app
          name: Create ArgoCD App
          action: cnoe:create-argocd-app
          input:
            appName: ${{parameters.projectName}}
            appNamespace: ${{parameters.projectName}}
            argoInstance: in-cluster
            projectName: default
            # necessary until we generate our own cert
            repoUrl: https://d2odpiejt3zpvd.cloudfront.net:443/gitea/giteaAdmin/${{parameters.projectName}}
            path: "manifests"
    - id: register
      name: Registro no catálogo
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'
        
 output:
    links:
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
